name: Auto Tag Repo

on:
  push:

jobs:
  auto-tag:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: check if latest commit has tag
        id: tag-missing
        run: echo "::set-output name=tag-missing::$(! git tag --points-at HEAD)"
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date '+%A_%b-%d-%Y_%H:%M')"
      - name: tag latest commit if not tagged
        uses: actions/github-script@v4
        with:
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/auto-deploy_${{steps.date.outputs.date}}",
              sha: context.sha
            })
