# Testing the commit-tag part from pearup Build App
# No actual cron used here to make testig easier
# Trigger here is a push to main with 'tag' in the commit message

name: Trigger Build

on:
  push:
    branches:
      - main

jobs:
  commit-tag:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'tag')"
    steps:
      - uses: hmarr/debug-action@v2
      - name: checkout the current HEAD
        with:
          token: ${{ secrets.ADMIN_ACCESS_TOKEN }}
        uses: actions/checkout@v2
      - name: check if the HEAD should be tagged triggering a new build
        id: tag-info
        run: |
          message="$(git log --format=%B -1)"
          skip=":rocket:(skip-ci):"
          sha="$(git log --pretty=%H -1)"
          date="$(TZ="CET" date '+%Y-%m-%d_%H-%M')"
          git fetch origin 'refs/tags/*:refs/tags/*'
          if [[ $message != *$skip* && ! $(git tag --points-at HEAD) ]]; then
            echo "::set-output name=create-tag::true"
            echo "::set-output name=sha::$sha"
            echo "::set-output name=date::$date"
          fi
      - name: create the tag depending on the check
        if: ${{ steps.tag-info.outputs.create-tag == 'true' }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a -m "scheduled tag to trigger deployment" deploy-master_${{steps.tag-info.outputs.date}}
          git push origin deploy-master_${{steps.tag-info.outputs.date}}
