name: Build App Test

on:
  push:
    branches:
      - staging
      - beta
    tags:
      - deploy-master**
  schedule:
    - cron: "5-15 0-4,14-23 * * 1-5" # those times are UTC -> CET '* 0-6,16-23 * * 1-5' weekdays at the full hour from 4pm to 6am
    - cron: "5-15 * * * 0,6" # weekends always at the full hour

jobs:
  register-deploy:
    runs-on: ubuntu-latest
    outputs:
      deploy: ${{ env.branch }}
      deploy-tag: ${{ env.branch }}-${{ steps.shorten-sha.outputs.sha }}
    steps:
      - name: DEBUG
        uses: hmarr/debug-action@v2
      - name: set deploy to false initially
        run: echo "branch=false" >> $GITHUB_ENV
      - name: on branch pushes to staging or beta extract the branch name from GITHUB_REF
        if: contains(github.event.ref, 'heads')
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
      - name: on valid tag pushes select master as deploy branch
        if: contains(github.event.ref, 'tags')
        run: echo "branch=master" >> $GITHUB_ENV
      - name: if it is a cron job check checkout the current HEAD
        if: ${{ github.event_name == 'schedule' }}
        uses: actions/checkout@v2
      - name: check if the HEAD is not tagged
        if: ${{ github.event_name == 'schedule' }}
        id: tag-missing
        run: git fetch origin 'refs/tags/*:refs/tags/*'; if [[ ! $(git tag --points-at HEAD) ]]; then echo "::set-output name=tag-missing::true"; fi;
      - name: if the HEAD is not tagged then set branch to deploy
        if: ${{ steps.tag-missing.outputs.tag-missing == 'true' }}
        run: echo "branch=master" >> $GITHUB_ENV
      - name: if the HEAD is not tagged then generate a tag date
        id: date
        run: echo "::set-output name=date::$(TZ="CET" date '+%Y-%m-%d_%H-%M')"
      - name: if the HEAD is not tagged then tag it
        if: ${{ steps.tag-missing.outputs.tag-missing == 'true' }}
        uses: actions/github-script@v4
        with:
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/auto-deploy_${{steps.date.outputs.date}}",
              sha: context.sha
            })
      - name: Split off first 7 characters of sha
        id: shorten-sha
        run: echo "::set-output name=sha::${GITHUB_SHA:0:7}"

  log-tag:
    runs-on: ubuntu-latest
    needs: register-deploy
    steps:
      - name: read deploy
        run: echo "${{ needs.register-deploy.outputs.deploy }}"
      - name: read deploy-tag
        run: echo "${{ needs.register-deploy.outputs.deploy-tag }}"

  conditional-job:
    runs-on: ubuntu-latest
    needs: register-deploy
    if: ${{ needs.register-deploy.outputs.deploy != 'false' }}
    steps:
      - name: read deploy
        run: echo "${{ needs.register-deploy.outputs.deploy }}"