# Testing the select-env part from pearup Build App
name: Build App

on:
  push:
    branches:
      - staging
      - beta
    tags:
      - deploy-master**

jobs:
  # This job builds performs a docker build to put the application
  # into a docker image. The image is then stored in a AWS ECR registry.
  select-env:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, ':rocket:(skip-ci):')"
    outputs:
      environment: ${{ env.environment }}
      image-tag: ${{ env.image-tag }}
    steps:
      - uses: hmarr/debug-action@v2
      - name: specify enviroment and image-tag on branch pushes to staging or beta
        if: contains(github.event.ref, 'heads')
        run: |
          echo "image-tag=${GITHUB_REF#refs/heads/}-${GITHUB_SHA:0:7}" >> $GITHUB_ENV
          echo "environment=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
      - name: specify enviroment and image-tag on valid tag pushes
        if: contains(github.event.ref, 'tags')
        run: |
          echo "image-tag=master-${GITHUB_SHA:0:7}" >> $GITHUB_ENV
          echo "environment=production" >> $GITHUB_ENV

      # logging only
      - name: log created envs
        run: |
          echo "${{ env.environment }}"
          echo "${{ env.image-tag }}"
