name: Trigger Build

on:
  schedule:
    - cron: "40,45 22 * * *" # times are UTC -> always at midnight

jobs:
  commit-tag:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the current HEAD
        uses: actions/checkout@v2
      - name: check if the HEAD should be tagged triggering a new build
        id: tag-info
        run: |
          message="$(git log --format=%B -1)"
          skip=":rocket:(skip-ci):"
          sha="$(git log --pretty=%H -1)"
          date="$(TZ="CET" date '+%Y-%m-%d_%H-%M')"
          if [[ $message != *$skip* ]]; then
            echo "::set-output name=create-tag::true"
            echo "::set-output name=sha::$sha"
            echo "::set-output name=date::$date"
          fi
      - name: create the tag depending on the check
        if: ${{ steps.tag-info.outputs.create-tag == 'true' }}
        uses: actions/github-script@v4
        with:
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/tag-test_${{steps.tag-info.outputs.date}}",
              sha: "${{steps.tag-info.outputs.sha}}"
            })
