name: Trigger Build

on:
  push:
    branches:
      - main

jobs:
  commit-tag:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the current HEAD
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ADMIN_ACCESS_TOKEN }}
      - name: check if the HEAD should be tagged triggering a new build
        id: tag-info
        run: |
          message="$(git log --format=%B -1)"
          skip=":rocket:(skip-ci):"
          sha="$(git log --pretty=%H -1)"
          date="$(TZ="CET" date '+%Y-%m-%d_%H-%M')"
          if [[ $message != *$skip* ]]; then
            echo "::set-output name=create-tag::true"
            echo "::set-output name=sha::$sha"
            echo "::set-output name=date::$date"
          fi
      - name: create the tag depending on the check
        if: ${{ steps.tag-info.outputs.create-tag == 'true' }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a -m "scheduled tag to trigger deployment" manual-deploy_${{steps.tag-info.outputs.date}}
          git push origin manual-deploy_${{steps.tag-info.outputs.date}}
