name: Test On Tag

on:
  create:
    tags:
      - auto-deploy**
      - manual-deploy**

jobs:
  register-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ env.branch }}-${{ steps.shorten-sha.outputs.sha }}
    steps:
      - uses: hmarr/debug-action@v2
      - name: on valid tag pushes select master as deploy branch
        if: contains(github.event.ref, 'tags')
        run: echo "branch=master" >> $GITHUB_ENV
      - name: Split off first 7 characters of sha
        id: shorten-sha
        run: echo "::set-output name=sha::${GITHUB_SHA:0:7}"

  log-tag:
    runs-on: ubuntu-latest
    needs: register-tag
    steps:
      - name: read tag
        run: echo "${{ needs.image-tag.outputs.tag }}"
        